### ISSUE TITLE
Saving of membrane potentials is not working

### ISSUE THREAD

**Issue by torbjone** [INM-6/hybridLFPy#27]
For certain cases, it might make sense to save the membrane potentials of the cells, and for example in the "example_brunel.py" file, "somav" is already in "savelist", which would indicate that it should be saved. This does however not seem to be working.

A hack that seemed to work locally was to add "recordSingleContribFrac=1," as an argument to the Population class in "example_brunel.py" (L334):
https://github.com/INM-6/hybridLFPy/blob/aec00dc019a5de8d5de1e07dfb1c4a9e23122463/examples/example_brunel.py#L334
and add "somav" to the list on line 755 in "population.py":
https://github.com/INM-6/hybridLFPy/blob/aec00dc019a5de8d5de1e07dfb1c4a9e23122463/hybridLFPy/population.py#L755

However, this will also save all single-cell extracellular potentials (and possible CSDs), which might be a bit overkill for large simulations. 
We should probably at least add "somav" to the list on line 755 in "population.py", or implement a new way to save somav without also saving all single cell LFP/CSD contributions.

Any thoughts?

**Comment by espenhgn** [comment]
Hi,
Perhaps this is better fixed when the LFPy@2.2.dev0 branch is patched into the hybridLFPy@nest3 branch. Then `savelist` should be for `LFPy.Cell` attributes exclusively and predictions made using `LFPykit.model` instances would be summed up and saved per population and in total by default. 

But if you need a quick fix, perhaps modify the `Population.collect_data` and `Postprocess.run()` method accordingly.

**Comment by espenhgn** [comment]
Closing this issue - this *should* now work in the current nest3 branch since merging #29. Note that this working branch requires LFPy@2.2.dev0 and NEST@master (tested with https://github.com/nest/nest-simulator/commit/24de43dc21c568e017839eeb335253c2bc2d487d) as outlined in this new Dockerfile recipe: https://github.com/INM-6/hybridLFPy/blob/nest3/examples/Hagen_et_al_2016_cercor/Dockerfile

**Comment by espenhgn** [comment]
Should add: `savelist` output should end up in the files `$SCRATCH/<simulation_output_folder>/populations/<Y>_savelist.h5`
